apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-rmq-sender-deployment
spec:
  selector:
    matchLabels:
      app: springboot-rmq-sender
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "9095"
      labels:
        app: springboot-rmq-sender
    spec:
      containers:
      - name: springboot-rmq-sender
        image: dockertestbaby/springboot-rmq-sender:1.0
        ports:
        - containerPort: 9095
        
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-rmq-sender-service
spec:
  type: ClusterIP
  selector:
    app: springboot-rmq-sender
  ports:
  - port: 9095
